spring:
  profiles:
    active: local

  kafka:
    topic: "library-events"
    producer:
      bootstrap-servers: localhost:9092,localhost:9093
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: com.learningkafka.library.config.CustomSerializerKafkaAvro
      properties:
        schema.registry.url: http://localhost:8085
    admin:
      properties:
        bootstrap-servers: localhost:9092,localhost:9093
    properties:
      schema.registry.url: http://localhost:8085
server:
  port: 8089
